version: "3.9"

services:
  backend:
    build: ./backend
    container_name: wine_backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017

  mongodb:
    image: mongo:6
    container_name: wine_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  recommender:
    build: ./recommender
    container_name: wine_recommender
    ports:
      - "8001:8001"

volumes:
  mongo_data:
